-- Canonical schema is versioned in migrations/001_durable_payments.sql.
-- Apply with npm run db:migrate using a separate server-side migration role.
-- Do not run schema changes during application startup or build.
