"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowRight, ChevronDown, ChevronUp } from "lucide-react";
import { Motif } from "@/components/illustrations/Motif";

const facts = [["Project relationship", "Hammad Foundation", "Education access mission; Lahore school project within YZ Educational Services"], ["Payment identity", "YZ Educational Services", "Payments are received by YZ and designated for Hammad Foundation"], ["Corporate record", "CUIN 0326364", "SECP record for YZ Educational Services (Private) Limited"], ["Evidence standard", "Review before publication", "Updates and learner media require appropriate review"]] as const;
const register = [["Project updates", "School and programme updates are published after review."], ["Payment records", "Transaction records are handled by YZ Educational Services."], ["Source evidence", "Supporting documents and vendor receipts are retained by the responsible operator."], ["Safeguarding review", "Learner media and profiles require consent and review before publication."]] as const;

export function TransparencySection() { const [expanded, setExpanded] = useState(false); return <section id="transparency" className="bg-white py-16 md:py-24"><div className="container"><div className="grid gap-7 lg:grid-cols-[1fr_.8fr] lg:items-end"><div><Motif kind="payment" size={66} /><p className="eyebrow mt-5">Governance</p><h2 className="mt-4 max-w-[17ch]">Support you can understand.</h2></div><p className="max-w-[53ch] text-lg body-muted">Hammad Foundation communicates its education mission and Lahore school work. YZ Educational Services operates the school project and receives payments.</p></div><dl className="mt-9 divide-y divide-brand-charcoal/15 border-y border-brand-charcoal/15">{facts.map(([label, value, detail]) => <div key={label} className="grid gap-2 py-5 sm:grid-cols-[12rem_1fr_1.2fr] sm:items-center"><dt className="font-bold text-brand-gray-500">{label}</dt><dd className="text-lg font-bold">{value}</dd><dd className="text-base body-muted">{detail}</dd></div>)}</dl><div className="mt-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><span className="text-base body-muted">Barki Road, Lahore</span><button type="button" onClick={() => setExpanded(!expanded)} className="link-arrow self-start" aria-expanded={expanded}>{expanded ? "Hide evidence register" : "View evidence register"}{expanded ? <ChevronUp size={18} /> : <ChevronDown size={18} />}</button></div>{expanded && <div className="mt-5 divide-y divide-brand-charcoal/15 border-y border-brand-charcoal/15">{register.map(([title, detail]) => <div key={title} className="grid gap-2 py-4 sm:grid-cols-[12rem_1fr]"><strong>{title}</strong><p className="text-base body-muted">{detail}</p></div>)}</div>}<Link href="/transparency" className="link-arrow mt-7">Read the full transparency record <ArrowRight size={18} /></Link></div></section>; }
