import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Building2, Landmark, ShieldCheck } from "lucide-react";
import { siteUrls } from "@/config/ecosystem";

export const metadata: Metadata = { title: "How We Are Structured | Hammad Foundation & YZ Educational Services", description: "The public relationship between Hammad Foundation and YZ Educational Services.", alternates: { canonical: "/how-we-are-structured" } };

export default function HowWeAreStructuredPage() {
  return <div className="min-h-screen bg-white"><section className="bg-brand-sand py-16 md:py-24"><div className="container max-w-6xl"><p className="text-xs font-bold uppercase tracking-[.16em] text-brand-nero">How we are structured</p><h1 className="mt-4 max-w-4xl text-5xl sm:text-6xl">Clear roles make support easier to understand.</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-secondary">Hammad Foundation and YZ Educational Services work together with distinct public and payment responsibilities.</p></div></section><section className="container py-16 md:py-24"><div className="grid border-y border-brand-charcoal/12 md:grid-cols-2"><article className="p-7 md:p-10"><Building2 size={25} className="text-brand-nero" /><p className="mt-8 text-xs font-bold uppercase tracking-[.16em] text-brand-nero">Education mission and school project</p><h2 className="mt-3 text-3xl">Hammad Foundation</h2><p className="mt-5 text-base leading-relaxed text-secondary">Communicates the education mission and the work of its Lahore school community.</p></article><article className="border-t border-brand-charcoal/12 bg-brand-navy p-7 text-white md:border-l md:border-t-0 md:p-10"><Landmark size={25} className="text-white" /><p className="mt-8 text-xs font-bold uppercase tracking-[.16em] text-white/65">Operating and payment entity</p><h2 className="mt-3 text-3xl text-white">YZ Educational Services</h2><p className="mt-5 text-base leading-relaxed text-white/72">Provides administration, governance, and the payment boundary. YZ Educational Services (Private) Limited holds SECP CUIN 0326364.</p></article></div><div className="mt-10 grid gap-7 md:grid-cols-[.85fr_1.15fr] md:items-start"><ShieldCheck size={26} className="text-brand-nero" /><div><h2 className="text-3xl">What this means for supporters</h2><p className="mt-4 max-w-3xl text-base leading-relaxed text-secondary">Hammad Foundation communicates its education work; the support page names YZ Educational Services (Private) Limited as recipient and Hammad Foundation as the designated project before a payment is created.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/donate" className="btn-brand">Support a student <ArrowRight size={16} /></Link><a href={siteUrls.yz} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center justify-center border border-brand-charcoal/20 px-5 text-sm font-semibold hover:bg-brand-sand">Visit YZ Educational Services</a></div></div></div></section></div>;
}
