import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, FileCheck2, MessageCircle } from "lucide-react";
import { siteUrls } from "@/config/ecosystem";

export const metadata: Metadata = { title: "Updates | Hammad Foundation", description: "Evidence-led public updates for Hammad Foundation.", alternates: { canonical: "/updates" } };

export default function UpdatesPage() {
  return <div className="min-h-screen bg-brand-sand py-16 md:py-24"><div className="container max-w-5xl"><p className="text-xs font-bold uppercase tracking-[.16em] text-brand-nero">Evidence-led updates</p><h1 className="mt-4 max-w-3xl text-5xl sm:text-6xl">School and project updates.</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-secondary">Public updates are added when the event, source, privacy review, and publishing owner are clear.</p><section className="mt-12 border-y border-brand-charcoal/12 bg-white p-7 md:p-10"><FileCheck2 size={26} className="text-brand-nero" /><h2 className="mt-7 text-3xl">No unverified updates are being displayed.</h2><p className="mt-4 max-w-2xl text-base leading-relaxed text-secondary">For current school information, contact the Hammad Foundation team. For support records and payment identity, use the YZ Educational Services project and transparency pages.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href={`${siteUrls.yz}/projects/hammad-foundation`} className="btn-brand">View YZ project page <ArrowRight size={16} /></a><a href="https://wa.me/923008099015?text=Hello%20Hammad%20Foundation%2C%20I%20would%20like%20to%20ask%20about%20current%20school%20information." target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center justify-center gap-2 border border-brand-charcoal/20 px-5 text-sm font-semibold hover:bg-brand-gray-50"><MessageCircle size={17} /> Contact the school team</a></div></section><Link href="/transparency" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-brand-nero hover:text-brand-navy">View transparency information <ArrowRight size={16} /></Link></div></div>;
}
