import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Motif } from "@/components/illustrations/Motif";

export const metadata: Metadata = { title: "Transparency & Governance | Hammad Foundation", description: "The Hammad Foundation relationship, payment identity, and public accountability commitments.", alternates: { canonical: "/transparency" } };
const records = [["Project relationship", "Hammad Foundation", "Education initiative with a Lahore school project of YZ Educational Services"], ["Payment recipient", "YZ Educational Services", "Y.Z Educational Services (Private) Limited"], ["Project designation", "Hammad Foundation", "Shown before a donor continues to payment"], ["Corporate record", "CUIN 0326364", "SECP incorporation record for YZ Educational Services"]] as const;
const commitments = [["Relationship before claims", "Hammad Foundation is dedicated to helping people access education. Its Lahore school project is part of YZ Educational Services. Claims about registration, tax status, or charitable status are not published without supporting evidence."], ["Payment identity before payment", "Support is routed to YZ Educational Services, with Hammad Foundation shown as the designated project before the donor continues."], ["Evidence before publication", "Programme updates should retain a source owner, event date, evidence location, safeguarding review, and review date before publication."], ["Privacy and safeguarding", "Learner stories, images, receipts, and personal information require appropriate consent and should never be used as unverified proof of impact."]] as const;

export default function TransparencyPage() { return <div className="bg-white"><section className="bg-brand-gray-50 py-14 md:py-20"><div className="container grid gap-7 lg:grid-cols-[1fr_.7fr] lg:items-end"><div><p className="eyebrow">Public accountability</p><h1 className="mt-4 max-w-[14ch]">Clear structure. Evidence-led updates.</h1></div><p className="max-w-[55ch] text-lg body-muted">This page explains what is verified, who handles payments, and how public information should be reviewed.</p></div></section><section className="container py-16 md:py-24"><div className="grid gap-7 lg:grid-cols-[.65fr_1fr]"><div><Motif kind="payment" size={72} /><p className="eyebrow mt-6">The public record</p><h2 className="mt-4 max-w-[15ch]">Names and roles, in plain sight.</h2></div><dl className="divide-y divide-brand-charcoal/15 border-y border-brand-charcoal/15">{records.map(([label, value, detail]) => <div key={label} className="grid gap-2 py-6 sm:grid-cols-[11rem_1fr]"><dt className="font-bold text-brand-gray-500">{label}</dt><dd><strong className="block text-xl">{value}</strong><span className="mt-1 block text-base body-muted">{detail}</span></dd></div>)}</dl></div></section><section className="bg-brand-gray-50 py-16 md:py-24"><div className="container"><p className="eyebrow">Our commitments</p><h2 className="mt-4 max-w-[16ch]">Care in what we publish.</h2><div className="mt-8 divide-y divide-brand-charcoal/15 border-y border-brand-charcoal/15">{commitments.map(([title, detail], index) => <article key={title} className="grid gap-4 py-6 md:grid-cols-[3rem_17rem_1fr] md:items-start"><span className="font-display text-xl font-extrabold tabular-nums text-brand-nero">0{index + 1}</span><h3 className="text-xl">{title}</h3><p className="max-w-[65ch] text-base body-muted">{detail}</p></article>)}</div><div className="mt-10 flex flex-col gap-5 rounded-2xl bg-white p-7 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="text-2xl">Have a question about a record or update?</h3><p className="mt-2 text-base body-muted">Speak to the team for current information.</p></div><Link href="/contact" className="btn-brand shrink-0">Contact the school team <ArrowRight size={17} /></Link></div></div></section></div>; }
