import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { relationshipDisclosure } from "@/config/ecosystem";
import { campusPhotoSrc } from "@/data/campus-photos";
import { Motif } from "@/components/illustrations/Motif";
import { LeadershipStory } from "@/components/landing/LeadershipStory";

export const metadata: Metadata = { title: "Our Story | Hammad Foundation", description: "The mission and operating relationship behind Hammad Foundation.", alternates: { canonical: "/our-story" } };

export default function OurStoryPage() { return <div className="bg-white"><section className="container grid gap-9 py-14 lg:grid-cols-12 lg:items-center lg:py-20"><div className="lg:col-span-6"><p className="eyebrow">Our story</p><h1 className="mt-4 max-w-[13ch]">Education opens doors. Community keeps them open.</h1><p className="mt-6 max-w-[55ch] text-lg body-muted">Hammad Foundation is dedicated to helping people access education. Its Lahore school community makes that purpose visible in everyday lessons, books, and the support that helps learning continue. YZ Educational Services operates the school project and receives payments.</p><Link href="/our-school" className="btn-brand mt-7">See the school <ArrowRight size={18} /></Link></div><figure className="lg:col-span-6"><div className="photo-frame aspect-[4/3]"><Image src={campusPhotoSrc("05-classroom-learning")} alt="Students studying with their books in a Hammad Foundation classroom" fill priority sizes="(min-width: 1024px) 48vw, 100vw" className="object-cover" /></div><figcaption className="mt-3 text-sm body-muted">Learning in the classroom · Photograph supplied by Hammad Foundation</figcaption></figure></section>
<LeadershipStory />
<section className="bg-brand-gray-50 py-16 md:py-24"><div className="container grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">The relationship</p><h2 className="mt-4 max-w-[15ch]">Two names. Clear roles.</h2></div><div className="divide-y divide-brand-charcoal/15 border-y border-brand-charcoal/15"><article className="grid gap-4 py-7 sm:grid-cols-[4rem_1fr]"><Motif kind="school" size={58} /><div><h3 className="text-2xl">The school project</h3><p className="mt-3 max-w-[60ch] text-base body-muted">Hammad Foundation shares its education mission and the work of its Lahore school community.</p></div></article><article className="grid gap-4 py-7 sm:grid-cols-[4rem_1fr]"><Motif kind="payment" size={58} /><div><h3 className="text-2xl">The operating relationship</h3><p className="mt-3 max-w-[60ch] text-base body-muted">{relationshipDisclosure} The relationship is shown on the website and in the support flow so the mission and payment identity remain connected.</p></div></article></div></div></section>
<section className="container grid gap-8 py-16 lg:grid-cols-[1fr_.8fr] lg:items-center md:py-24"><div><p className="eyebrow">Confidence through clarity</p><h2 className="mt-4 max-w-[19ch]">Know who receives your support.</h2><p className="mt-5 max-w-[60ch] text-lg body-muted">YZ provides the secure support route, shows the payment recipient and Hammad designation, and publishes public records only when they have a source and review owner.</p><Link href="/how-we-are-structured" className="link-arrow mt-6">Learn how the relationship is structured <ArrowRight size={17} /></Link></div><div className="art-panel aspect-[1.5] bg-[#E9F8ED] p-5"><Image src="/images/hammad/illustrations/guardian-bridge.webp" width={1448} height={1086} sizes="(min-width: 1024px) 40vw, 100vw" alt="Conceptual green pathway joining learning materials to an open school door" className="h-full w-full object-contain" /></div></section></div>; }
